import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../Components/header'

export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.grid}>
          <Header />
         
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://jennie-michele.0.capacedev.se/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Jennie och Michele {' '}
          <span className={styles.logo}>
            <Image src="/favicon.ico" alt="Vercel Logo" width={13} height={13} />
          </span>
        </a>
      </footer>
    </div>
  )
}
